# Generated by Django 5.1.1 on 2024-10-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_delete_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('year_published', models.IntegerField()),
                ('borrow_time', models.IntegerField(choices=[(10, 'Type_1'), (5, 'Type_2'), (2, 'Type_3')], default=10)),
                ('filename', models.ImageField(blank=True, null=True, upload_to='book_images/')),
                ('status', models.CharField(choices=[('available', 'Available'), ('loaned', 'Loaned'), ('erased', 'Erased')], default='available', max_length=20)),
            ],
        ),
    ]
