# Generated by Django 5.1.1 on 2024-10-20 13:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Loandate', models.DateField(default=django.utils.timezone.now)),
                ('Returndate', models.DateField(blank=True, null=True)),
                ('BookID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.book')),
                ('CustID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.customer')),
            ],
        ),
    ]
