version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: library
    volumes: 
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # how to get to the init.sql file
    ports:
      - "5432:5432"
    networks:
      pg_network:  # Changed from a list to a dictionary format
        ipv4_address: 172.19.0.2

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    networks:
      pg_network:  # Changed from a list to a dictionary format
        ipv4_address: 172.19.0.3

networks:
  pg_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
